/* ------------------------------- App Related ------------------------------ */
export enum EFlag {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ERROR_OCCURED = 'ERROR_OCCURED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_GONE = 'RESOURCE_GONE',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  DATA_EMPTY = 'DATA_EMPTY',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  UPLOAD_FAIL = 'UPLOAD_FAIL',
  ERROR_VALIDATION = 'ERROR_VALIDATION',
  INVALID_HEADERS = 'INVALID_HEADERS',
  INVALID_BODY = 'INVALID_BODY',
  INVALID_PARAM = 'INVALID_PARAM',
  INVALID_JWT = 'INVALID_JWT',
  INVALID_GOOGLE_TOKEN = 'INVALID_GOOGLE_TOKEN',
  WRONG_CODE = 'WRONG_CODE',
  REFERRAL_ALREADY_USED = 'REFERRAL_ALREADY_USED',
  DEVICE_ALREADY_USED = 'DEVICE_ALREADY_USED',
  PHONE_NOT_VERIFIED = 'PHONE_NOT_VERIFIED',
  BASIC_AUTH_UNAUTHORIZED = 'BASIC_AUTH_UNAUTHORIZED',
  MISSING_REQUIREMENT = 'MISSING_REQUIREMENT'
}
/* --------------------------- End of App Related --------------------------- */
