name: Integration Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  integration-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build image
      run: docker build --target builder -t scrapper-app .

    - name: Execute integration test
      run: npm run test:container

    - name: Stop containers
      run: docker-compose down